#.travis.yml

language: node_js
node_js:
  - '11'
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

matrix:
    include:
        - env: PROJECT=projects/projectA
        - env: PROJECT=projects/projectB

script: if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $PROJECT; then echo "$PROJECT is being built"; else echo "$PROJECT is NOT being built"; fi


before_script:
  - npm install -g @angular/cli

script:
  - npm ci
  - ng lint
  - npm run test:ci
  - npm run build:prod -- --base-href https://<my-page>.github.io/<dest-folder>/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $git_token
  local_dir: dist/<dest-folder>

notifications:
  email:
    on_failure: change
    on_success: change